### ISSUE TITLE
 iwi kurcheelena 

### ISSUE THREAD

**Issue by PhyloStar** [PhyloStar/UDTelugu#7]
@nishkalavallabhi  refers iwi as PRON. But, I think it is DET. Have to resolve...

**Comment by nishkalavallabhi** [comment]
I think it is  PRON because it refers to a Noun which is an object kurcheelu.

**Comment by PhyloStar** [comment]
I marked it as PRON. SO, there is no issue ??

**Comment by nishkalavallabhi** [comment]
I reopened the issue :-)

in 
idi naa kalam
and other such sentences, I am seeing idi etc as Pronouns. They are tagged as DET now. My question is: can a DET even be an nsubj to a noun? If it is a DET, shouldn't the dependency relation be a det and not nsubj? I think they are all pronouns because they substitute for a noun/refer to a noun.  

edi, ekkada, evaru etc - can be argued as interrogative determiners as you mentioned in the other issue. But perhaps not idi, adi etc?

**Comment by PhyloStar** [comment]
Exactly. I have the same question. I am just making a choice of nsubj after discussing with Viswanath. My understanding from UD guidelines is that pronouns are mainly personal. whereas, this, that are determiners something which the grammar book also says.

**Comment by nishkalavallabhi** [comment]
Am closing this issue as we seem to have resolved the DET vs PRON issues now.
